# docker-compose.pulsar.test.yml
# Compose file for running Pulsar integration tests in Docker
# Use this instead of the main compose for platform-agnostic, CI/CD-safe testing

services:
  zookeeper:
    image: apachepulsar/pulsar:3.1.0
    container_name: zookeeper
    restart: on-failure
    networks:
      - pulsar
    volumes:
      - pulsar-zookeeper-data:/pulsar/data
    environment:
      - metadataStoreUrl=zk:zookeeper:
      - PULSAR_PREFIX_bookiePort=3181
      - ZOO_DATA_DIR=/pulsar/data/zookeeper
      - ZOO_DATA_LOG_DIR=/pulsar/data/zookeeper
    command: |
      bash -c "bin/apply-config-from-env.py conf/zookeeper.conf && \
             bin/generate-zookeeper-config.sh conf/zookeeper.conf && \
             exec bin/pulsar zookeeper"
    healthcheck:
      test: ["CMD", "bin/pulsar-zookeeper-ruok.sh"]
      interval: 20s
      timeout: 10s
      retries: 30
      start_period: 30s

  pulsar-init:
    container_name: pulsar-init
    hostname: pulsar-init
    image: apachepulsar/pulsar:3.1.0
    networks:
      - pulsar
    command: >
      bin/pulsar initialize-cluster-metadata
      --cluster cluster-a
      --zookeeper zookeeper:2181
      --configuration-store zookeeper:2181
      --web-service-url http://broker:8080
      --broker-service-url pulsar://broker:6650
    depends_on:
      zookeeper:
        condition: service_healthy

  bookie:
    image: apachepulsar/pulsar:3.1.0
    container_name: bookie
    restart: on-failure
    command:
      - bash
      - -c
      - |
        bin/apply-config-from-env.py conf/bookkeeper.conf &&
        exec bin/pulsar bookie
    volumes:
      - ./data/bookkeeper:/pulsar/data/bookkeeper
    environment:
      - zkServers=zookeeper:2181
      - metadataServiceUri=metadata-store:zk:zookeeper:2181
      - advertisedAddress=bookie
      - bookieId=bookie
      - PULSAR_MEM=-Xms512m -Xmx512m -XX:MaxDirectMemorySize=512m
      - bookiePort=3181
      - journalDirectory=/pulsar/data/bookkeeper/journal
      - ledgerDirectories=/pulsar/data/bookkeeper/ledgers
    networks:
      - pulsar
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "netstat", "-lntp", "|", "grep", "3181"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  broker:
    image: apachepulsar/pulsar:3.1.0
    container_name: broker
    hostname: broker
    restart: on-failure
    networks:
      pulsar:
        aliases:
          - pulsar-broker
    environment:
      - metadataStoreUrl=zk:zookeeper:2181
      - zookeeperServers=zookeeper:2181
      - configurationMetadataStoreUrl=zk:zookeeper:2181
      - clusterName=cluster-a
      # Change these to allow external connections from host 
      - advertisedAddress=localhost
      - advertisedListeners=external:pulsar://localhost:6650
      - PULSAR_PREFIX_advertisedListeners=external:pulsar://localhost:6650
      - PULSAR_PREFIX_brokerServiceURLTLS=
      - PULSAR_PREFIX_brokerClientOperationTimeoutSeconds=10
      - PULSAR_PREFIX_brokerClientSocketTimeoutSeconds=10
      - managedLedgerDefaultEnsembleSize=1
      - managedLedgerDefaultWriteQuorum=1
      - managedLedgerDefaultAckQuorum=1
      - webServicePort=8080
      - brokerServicePort=6650
      - PULSAR_MEM=-Xms512m -Xmx512m -XX:MaxDirectMemorySize=256m
      - bookkeeperClientHealthCheckEnabled=true
    depends_on:
      zookeeper:
        condition: service_healthy
      bookie:
        condition: service_healthy
      pulsar-init:
        condition: service_completed_successfully
    ports:
      - "6650:6650"
      - "8080:8080"
    command: bash -c "bin/apply-config-from-env.py conf/broker.conf && exec bin/pulsar broker"
    healthcheck:
       test: ["CMD-SHELL", "curl -f http://localhost:8080/admin/v2/brokers/health || exit 1"]
       interval: 15s
       timeout: 10s
       retries: 12
       start_period: 60s

  test-runner:
    build:
      context: ../../../../../
      dockerfile: backend/app/core/pulsar/docker/Dockerfile.test
    container_name: test-runner
    depends_on:
      broker:
        condition: service_healthy
    networks:
      - pulsar
    environment:
      - PULSAR_SERVICE_URL=pulsar://broker:6650
    restart: on-failure
    command: ./run_integration_tests.sh

volumes:
  pulsar-zookeeper-data:
  pulsar-bookie-data:

networks:
  pulsar:
    driver: bridge
